apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: octobercms
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              value: root
            - name: DB_TYPE
              value: mysql
            - name: DB_USERNAME
              value: root
          image: aspendigital/octobercms:latest
          name: web
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
